version: '3.8'

services:
  mc_notification:
    build: .
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/kittydelivery
    networks:
      - shared-net

networks:
  shared-net:
    external: true
